### ISSUE TITLE
Cambiar colores de jugadores

### ISSUE THREAD

**Issue by albsierra** [ColaboraGIT/Snakes-and-Ladders#11]
https://github.com/ColaboraGIT/Snakes-and-Ladders/blob/29338187d9cf31e9fbb19127031567287ebb60c9/src/css/players.css#L9

Cambia los colores asociados a los jugadores. Si, además de cambiar los colores de los jugadores, consideras necesario modificar alguna otra característica de los jugadores, ¡Adelante!

**Comment by PabloFernandez4** [comment]
Listo
