### ISSUE TITLE
Imagen ganador 1

### ISSUE THREAD

**Issue by albsierra** [ColaboraGIT/Snakes-and-Ladders#17]
Cambia la imagen ![Ganador player 1](https://raw.githubusercontent.com/ColaboraGIT/Snakes-and-Ladders/master/src/images/winning-cat1.png) (/src/images/winning-cat1.png) por una como ![](https://www.flaticon.es/svg/static/icons/svg/562/562816.svg)

**Comment by josejuan1981** [comment]
Finalizado
