### ISSUE TITLE
Descripción del juego 5 líneas

### ISSUE THREAD

**Issue by albsierra** [ColaboraGIT/Snakes-and-Ladders#4]
https://github.com/ColaboraGIT/Snakes-and-Ladders/blob/29338187d9cf31e9fbb19127031567287ebb60c9/src/Home.js#L10
Traduce las 5 líneas correspondientes a la descripción del juego.

**Comment by GonxFH** [comment]
Closes #4

**Comment by GonxFH** [comment]
Closes #4
